# -*- coding: utf-8 -*-
"""estudo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8wT9OJbOZM8uveqt8h5DHZzOezdldb6
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install -q torch torchvision torchaudio
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5
!pip install -qr requirements.txt

from google.colab import files
uploaded = files.upload()

!unzip YOLO_dataset.zip -d YOLOv5/

dataset_path = '/content/yolov5/YOLOv5/obj/dataset.yaml'


yaml_content = """
train: /content/yolov5/YOLOv5/obj/images/train
val: /content/yolov5/YOLOv5/obj/images/val
test: /content/yolov5/YOLOv5/obj/images/test

nc: 2
names: ['chita', 'leao']
"""


with open(dataset_path, 'w') as file:
    file.write(yaml_content)

!python train.py --img 640 --batch 16 --epochs 50 --data /content/yolov5/YOLOv5/obj/dataset.yaml --weights yolov5s.pt --device 0

!pip install torch torchvision torchaudio
!pip install matplotlib opencv-python
!pip install pycocotools

from google.colab import files
uploaded = files.upload()

!unzip predict.zip -d predict/

import torch


model = torch.hub.load('ultralytics/yolov5', 'custom', path='/content/yolov5/runs/train/exp/weights/best.pt', force_reload=True)
model.eval()

!python detect.py --source /content/yolov5/predict/predict --weights runs/train/exp2/weights/best.pt --img-size 640 --conf-thres 0.15 --iou-thres 0.45 --device 0

import os
from IPython.display import Image, display


image_folder = 'runs/detect/exp13'

image_files = [f for f in os.listdir(image_folder) if f.endswith('.jpg') or f.endswith('.jpeg')]


for image_file in image_files:
    display(Image(filename=os.path.join(image_folder, image_file)))

